api/dev.js
plugins/exceptions.js

2 issues are addressed with this PR:
1. Process exception handlers were being added again every time the server was restart in dev mode
2. TS version of the server file was not refreshing when the server was restarted because its built file was only done 1x on initial server load
This PR fixes these 2 issues.

ensure ts server file is rebuilt and prevent process handlers being readded on server restart

---

api/dev.js
cli.js
package.json

This PR cleans up the terminal output of the cli in dev mode.
* coloured messages
* clear terminal noise between runs and when rebuilding bundles and restarting the server
For example:

print coloured information messages and clear console on restarts and rebundles

---

api/dev.js

The dist folder was throwing an error on a fresh install. Just needed to pre create the folder which this PR does.

fix: create dist folder ahead of time

---

api/start.js
lib/config.js
test/api/start.test.js

Adds a set of happy path e2e tests.
Tests cover
* starting and building the app
* validation
* manifest
* scripts
* content
* fallback
* lazy script loading
During the process of writing these tests, the following changes needed to be made:
* api/start.js now returns an object with an `address` property and a `close` function so that the server can be shutdown.
* setting the log level now works
* passing in cwd to /lib/plugin.js now works properly
* In its most basic case, the app can be run without a package.json file (though as soon as you add a content.js file, you need to have lit installed)

Add e2e tests

---

api/dev.js

This fixes an issue where the loading of a podlet would just hang and not properly load on some (random) machines in dev mode when a server.js file was present in the project. For those this would happen, the server would also output `Premature close` errors in the log.
```sh
[09:22:47 UTC] ERROR: premature close
reqId: "req-7"
err: {
"type": "Error",
"message": "premature close",
"stack":
Error: premature close
at onclosenexttick (/home/trygve/dev/podium/podlet-server/node_modules/end-of-stream/index.js:54:86)
at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
}
```
What causes this is that in dev mode the whole plugin is loaded twice into fastify when the file system listener for live reloads is attached. This would result in a server which holds a duplicate …

fix: Fix premature close

---

package.json

Repository pointing to labs repo makes semantic release fail.

ci: Fix repository

---

lib/config-schema.js
lib/config.js
test/lib/config.test.js

While still allowing the user to override this value as they see fit, app shutdown grace is defaulted to 5000 and set to 0 for development.
Fixes https://github.com/podium-lib/podlet-server/issues/14

feat: set grace to 0 in dev, default to 5000 and allow override

---

lib/plugin.js
plugins/dependencies.js
test/plugins/plugins-dependencies.test.js

Use `http-errors` when dealing with serving http errors. This align with what developers of podlets should do while it also avoids dealing with returning / sending errors in routes (its delegated to the error handler instead).

fix: Use http-errors on internal errors

---

GUIDE_DOCUMENT.md
README.md
lib/plugin.js
plugins/document.js
test/plugins/plugins-document.test.js

Adds support for Podium document templates via a document.js or .ts file

feat: add document.js to support Podium document template

---

api/index.js
api/test.js
lib/plugin.js
package.json

This PR adds a built in test server that can be used to write test tests for podlets
The API surface looks like:
```js
import { TestServer } from "@podium/podlet-server/test";
const server = await TestServer.create();
await server.build();
await server.start();
await server.stop();
```
The server is started on a random port and the applications files such as content.js, fallback.js etc are all read and used as if the server was running in prod.
A larger example using Tap looks like:
```js
import tap from 'tap';
import { TestServer } from "@podium/podlet-server/test";
// start the test server
const server = await TestServer.create();
await server.build();
await server.start();
tap.test('manifest file renders correctly', async (t) => {
const result = await fetch(server.routes.manifest); …
```

feat: add test server for testing applications

---

api/build.js

This PR fixes an issue with the build as follows:
When an entrypoint such as content.js includes files in src, Esbuild won't actually process those files when bundle is not set to true. Since we use Esbuild here to strip TS types and apply plugins only, we don't want bundle: true. In other words, there's no setting in Esbuild (as there is in Rollup) that allows you to build a directory of files and maintain their structure. 
My approach here was to use esbuild to resolve the files in the build and then for each file, run an Esbuild to build it from its source location to its destination and strip types and apply plugins. After this, Rollup is used to produce an optimal production build.

Fix build script

---

api/build.js
api/dev.js
lib/plugin.js
package.json
plugins/hydrate.js
plugins/ssr.js
test/plugins/plugins-hydrate.test.js
test/plugins/plugins-ssr.test.js

Fixes an issue with Safari and FF where the DSD ponyfill was not working correctly and so podlets were displaying a blank page. This was due to my own naive implementation which did not cover nesting. The implementation in this PR is comprehensive but costs 1.2kb. This is ok since it is only shipped if the browser does not support DSD. In practice, this will soon mean only Firefox since Safari has early/experimental support in the latest version and Chrome already fully supports DSD.

fix: replace dsd ponyfill with more comprehensive implementation

---

lib/plugin.js
plugins/docs.js
plugins/docs/handlers/configuration.get.js
plugins/docs/handlers/docs.get.js
plugins/docs/handlers/extensions.get.js
plugins/docs/handlers/routes.get.js
plugins/validation.js

Creates a series of auto generated documentation pages for the podlet which include information on routes, configuration and loaded extensions.

feat: add auto documentation pages

---

api/start.js
lib/config.js

Tweak to logging to make it easier to see which host and env an app is running in

fix: log host and env on info when app starts

---

lib/plugin.js

We have decided that headers should not be validated by default. This PR fixes that.

fix: remove header validation as headers should not be validated by default

---

lib/plugin.js
plugins/import-element.js
plugins/metrics.js

This PR:
* fixes a bug where many core metrics were not being consumed by awaiting plugin registration.
* adds additional metrics in the import element module to measure the time taken to bundle and load files

fix: ensure metrics are properly streamed. Add additional metrics for import element

---

lib/state.js

This PR injects the installed version of Convict into extension schema functions in order for them to be able to register formatters etc.

feat: inject convict object into extensions schema function

---

api/dev.js
api/start.js
api/test.js

We've seen that its pretty common to run apps with debug info in prod and Fastify does by default log requests to level info which becomes a lot of logs in a busy server. This turns request logging off.

fix: Disable request logging

---

lib/plugin.js

This was causing an issue where if the app was running with an app.base path of / then url references to hydrate support included two leading / characters which broke things. This PR runs the url path through a function to ensure all / characters are singular.

fix: ensure url paths have correct number of slash characters

---

api/dev.js
commands/dev.js
lib/config-schema.js
lib/config.js
lib/lingui-compile.js
lib/lingui-config.js
lib/plugin.js
plugins/live-reload.js
test/lib/plugin.test.js
test/plugins/plugins-live-reload.test.js

This PR moves file watching and the web socket server out of fastify plugins.
The motivation for this is threefold:
1. Perf: when the ws and file watching are inside a plugin, they must be shut down and re setup on every server restart
2. Ease: I've found it a challenge to try to cleanly shut down the web socket in particular on each server restart. Intermittent server hangs have been hard to avoid. With this PR, this stops being a challenge.
3. Reuse: Managing the file watcher and ws at the top level and passing it down to plugins means that other plugins can also make use of the file watcher and respond when files change.
Thoughts @trygve-lie?

fix: refactor file watching and ws out of plugins

---

api/dev.js
lib/pino-dev-transport.js
plugins/import-element.js
plugins/live-reload.js

Introducing a slight delay to reload seems to dramatically reduce the number of intermittent errors (with this PR in my testing I only managed to make the error occur 1x) when live reloading the page. The error seems to relate to a failed request to the server after the server is restarted.
Changes to config files no longer reloads the server. Instead, the user is informed that they need to manually restart the server due to a configuration change. Config files can't easily be reloaded as part of the change and reload cycle so its best to just inform the user and let them reload.
Fixes rare bug on reload where the custom element registry gets an undefined value.

fix: prevent undefined registry error and further reduce intermittent page reload delay error

---

lib/plugin.js
plugins/bundler.js
plugins/hydrate.js
plugins/ssr.js
test/plugins/plugins-bundler.test.js

Bit of a bug crept in there with the latest changes. This should address.
Dynamic URLs are for development mode only and assets such as the template shadow root should be fetched from the configured base path (usually a CDN) in production.

fix: do not use development bundling urls in non development context

---

api/test.js
test/api/memory-destination.js
test/api/server.test.js

This PR adds makes the `TestServer` use the configuration setting `app.logLevel` enabling you to choose the log level for your instance.
A side effect of testing this new behaviour is that the `create` method takes in a new property, `loggerFunction`. Enabling the tests added in `test/api/server.test.js` to verify that we actually do change the log levels.
Not super happy about the use of the `state` in here, so please come with suggestions 🙏

Making TestServer comply with the log level set in the configuration

---

GUIDE_EXTENSIONS.md
api/build.js
api/dev.js
api/test.js
lib/state.js
test/api/build.test.js

This PR makes available the entire `config` object inside build plugins for authors to use. This is done in a non-breaking manner by adding an optional configuration parameter on the `build` method configuration object in the `State` class.
With this feature you can now write your build plugins using the configuration from the server 👇 👇 
```
export const build = (config) => [{
name: "my-sweet-build-plugin",
setup(build) {
// here is how you use it inside your build plugin
config.get("some.property.for.build")
}
}]
```
Where the `config` argument is a Convict configuration object from the server(s). This feature is available in the dev, test and production versions of the server.

Enabling build plugins to get passed config

---

GUIDE_CONFIG.md
lib/config.js
test/lib/config.test.js

This PR looks to make the naming scheme for configuration overrides a bit nicer 💅 
```
config/host/<hostname>/config.<env>.json
```
```
config/host/<hostname>/<env>.json
```
We omit the "config" from the file name 🤷 
If you use the old format, we print a deprecation warning:
```
Deprecation warning: Your config override use an outdated path "config/hosts/example.com/config.prod.json". The new format
is: "config/hosts/example.com/prod.json"
```
Ideally this should have been logged with a logger, but this should be handled in a different PR.

fix: config override files are on config/host/<hostname>/<env>.json

---

api/build.js

I noticed when I tried to change a podlet from `ssr-only` to `hydrate`, the build broke because of a top-level await with some message about how it isn't supported in IIFE, which is the default output. The previous `esbuild` is configured with ESM output, so I figure we might have intended to do that for all of it?

Support top level await

---

lib/plugin.js
package.json
plugins/script.js
test/api/start.test.js
test/lib/plugin.test.js
test/plugins/plugins-csr.test.js
test/plugins/plugins-hydrate.test.js
test/plugins/plugins-ssr.test.js

- Fixes a bug where we'd render dev script tags in production
- Sets an environment variable for unit tests to workaround a bug in Lit
- Read Lit version from package.json instead of testing with wildcard
Context: https://github.com/podium-lib/podlet-server/pull/78#discussion_r1373274935

fix: don't include dev scripts in prod for hydration mode

---

api/build.js
package.json

`esbuild` would do this for our own code, but I've seen an issue where a dependency bundled by Rollup expected us to do this type of replacement ([lingui-core](https://github.com/lingui/js-lingui/blob/04b7cef9876168bc376b55424ecc0b0ebde976c1/packages/core/src/i18n.ts#L198)).

Replace process.env.NODE_ENV on client-side for dependencies
